# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='highlight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='highlights.Highlight'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlights', to='highlights.Channel'),
        ),
    ]
