# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0002_auto_20180409_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
