export const SET_PENDING_CHANGES  = 'SET_PENDING_CHANGES';
export const UPDATE_DOCUMENT_DATA  = 'UPDATE_DOCUMENT_DATA';
export const CLEAR_EDIT  = 'CLEAR_EDIT';


export const UPDATE_ANNOTATION_DATA  = 'UPDATE_ANNOTATION_DATA';
export const REMOVE_ANNOTATION  = 'REMOVE_ANNOTATION';
