export const FILE_DOWNLOADED = 'FILE_DOWNLOADED';
export const HIGHLIGHT_SAVED = 'HIGHLIGHT_SAVED';
export const FILE_UPLOAD_PROGRESS = 'FILE_UPLOAD_PROGRESS';
export const FILE_CALLBACK_SUCCESS = 'FILE_CALLBACK_SUCCESS';
