# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180407_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oss',
            old_name='mime_type',
            new_name='mimeType',
        ),
    ]
