# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180408_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oss',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='osses', to='projects.Paper'),
        ),
    ]
